version: '3.9'

services:
  server:
    container_name: stable-diffusion
    build: .

    ipc: host

    ports:
      - "18000:8000"
      - "18001:8001"
      - "18002:8002"

    environment:
      TZ: "Asia/Seoul"
      CUDA_VISIBLE_DEVICES: 0

    volumes:
      - ./models:/models
    tty: true
    command: tritonserver --model-repository=/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
